CREATE SCHEMA IF NOT EXISTS geek DEFAULT CHARACTER SET utf8 ;

CREATE TABLE USER (ID BIGINT AUTO_INCREMENT NOT NULL, BLABLA TINYINT(1) default 0, EMAIL VARCHAR(255), FUMEUR TINYINT(1) default 0, GENRE VARCHAR(255), NOM VARCHAR(255), PRENOM VARCHAR(255), PWD VARCHAR(255), TELEPHONE VARCHAR(255), Adress_id BIGINT, PRIMARY KEY (ID))
CREATE UNIQUE INDEX INDEX_USER_email ON USER (email)
CREATE TABLE ADRESS (ID BIGINT AUTO_INCREMENT NOT NULL, CODEPOSTAL VARCHAR(255), NUMRUE VARCHAR(255), PAYS VARCHAR(255), VILLE VARCHAR(255), COORDONNEES_ID BIGINT, PRIMARY KEY (ID))
CREATE UNIQUE INDEX INDEX_ADRESS_coordonnees ON ADRESS (coordonnees)
CREATE TABLE EPOINT (ID BIGINT AUTO_INCREMENT NOT NULL, LAT DOUBLE, LNG DOUBLE, PRIMARY KEY (ID))
CREATE UNIQUE INDEX INDEX_EPOINT_lat_lng ON EPOINT (lat, lng)
CREATE TABLE ADRESS_USER (Adress_ID BIGINT NOT NULL, users_ID BIGINT NOT NULL, PRIMARY KEY (Adress_ID, users_ID))
ALTER TABLE USER ADD CONSTRAINT FK_USER_Adress_id FOREIGN KEY (Adress_id) REFERENCES ADRESS (ID)
ALTER TABLE ADRESS ADD CONSTRAINT FK_ADRESS_COORDONNEES_ID FOREIGN KEY (COORDONNEES_ID) REFERENCES EPOINT (ID)
ALTER TABLE ADRESS_USER ADD CONSTRAINT FK_ADRESS_USER_Adress_ID FOREIGN KEY (Adress_ID) REFERENCES ADRESS (ID)
ALTER TABLE ADRESS_USER ADD CONSTRAINT FK_ADRESS_USER_users_ID FOREIGN KEY (users_ID) REFERENCES USER (ID)
