CREATE SCHEMA IF NOT EXISTS geek DEFAULT CHARACTER SET utf8 ;





CREATE TABLE  IF NOT EXISTS `epoint` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LAT` double DEFAULT NULL,
  `LNG` double DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `INDEX_EPOINT_lat_lng` (`LAT`,`LNG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE  IF NOT EXISTS `adress` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CODEPOSTAL` varchar(45) DEFAULT NULL,
  `NUMRUE` varchar(255) DEFAULT NULL,
  `PAYS` varchar(45) DEFAULT NULL,
  `VILLE` varchar(45) DEFAULT NULL,
  `COORDONNEES_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `INDEX_ADRESS_coordonnees` (`COORDONNEES_ID`),
  CONSTRAINT `FK_ADRESS_COORDONNEES_ID` FOREIGN KEY (`COORDONNEES_ID`) REFERENCES `epoint` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE  IF NOT EXISTS `user` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BLABLA` tinyint(1) DEFAULT '0',
  `EMAIL` varchar(255) DEFAULT NULL,
  `FUMEUR` tinyint(1) DEFAULT NULL,
  `GENRE` varchar(45) DEFAULT NULL,
  `NOM` varchar(45) DEFAULT NULL,
  `PRENOM` varchar(45) DEFAULT NULL,
  `PWD` varchar(45) DEFAULT NULL,
  `TELEPHONE` varchar(45) DEFAULT NULL,
  `Adress_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `INDEX_USER_email` (`EMAIL`),
  KEY `FK_USER_Adress_id_idx` (`Adress_id`),
  CONSTRAINT `FK_USER_Adress_id` FOREIGN KEY (`Adress_id`) REFERENCES `adress` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE  IF NOT EXISTS `adress_user` (
  `Adress_ID` bigint(20) NOT NULL,
  `user_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`Adress_ID`,`user_ID`),
  KEY `FK_ADRESS_USER_users_ID_idx` (`user_ID`),
  CONSTRAINT `FK_ADRESS_USER_Adress_ID` FOREIGN KEY (`Adress_ID`) REFERENCES `adress` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ADRESS_USER_users_ID` FOREIGN KEY (`user_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



