ALTER TABLE USER DROP FOREIGN KEY FK_USER_Adress_id
ALTER TABLE ADRESS_USER DROP FOREIGN KEY FK_ADRESS_USER_Adress_ID
ALTER TABLE ADRESS_USER DROP FOREIGN KEY FK_ADRESS_USER_users_ID
DROP TABLE USER
DROP TABLE ADRESS
DROP TABLE ADRESS_USER
