ALTER TABLE USER DROP FOREIGN KEY FK_USER_Adress_id
ALTER TABLE ADRESS DROP FOREIGN KEY FK_ADRESS_COORDONNEES_ID
ALTER TABLE ADRESS_USER DROP FOREIGN KEY FK_ADRESS_USER_Adress_ID
ALTER TABLE ADRESS_USER DROP FOREIGN KEY FK_ADRESS_USER_users_ID
DROP INDEX INDEX_USER_email ON USER
DROP TABLE USER
DROP INDEX INDEX_ADRESS_coordonnees ON ADRESS
DROP TABLE ADRESS
DROP INDEX INDEX_EPOINT_lat_lng ON EPOINT
DROP TABLE EPOINT
DROP TABLE ADRESS_USER
